language: cpp

matrix:
  include:
  - os: osx
    name: "Build"
    osx_image: xcode11.6
    compiler: clang

    script:
      - git clone https://github.com/acidanthera/MacKernelSDK
      - src=$(/usr/bin/curl -Lfs https://raw.githubusercontent.com/acidanthera/Lilu/master/Lilu/Scripts/bootstrap.sh) && eval "$src" || exit 1
      - xcodebuild -jobs 1 -configuration Debug
      - xcodebuild -jobs 1 -configuration Release

    deploy:
      provider: releases
      skip_cleanup: true
      file: "build/*/*/*.zip"
      file_glob: true
      api_key:
        secure: atJs/IEuSVDYzFYRi41DzaPooIxWocFJSQB9s8rrWUjmJd2MvrwfvSTmKlNDjSbkucYXURMwVUIy0sSaAT2lI8Zi4KUgmmEjT5jwoOCieo2pkuD3h0h+fuYV8IUDOl5/Z+kbdQdVPyWmZ0cPOVsII4qk6uHa38hrbm2cA6ey1re5nQowapidmB3FCJt2StYTr4ss8k/1+5tcSmEs5k3U2RYtY3oxrVVMUVVucH4ja8bpi58oSLBBDLhI58NYzO/XI+90nEFyUdYTlLSYxV+1lBDOj78p82CSVMSYUNcz11EvMmrBnYKFhtyofNrXtcoZeP/wX7Xc7kt9YFAmVl0om+ZSssQPNmJuViauHY4hRl71qA9P7cdx+bWDZQZOWOStXtI3DYo8eWdbFBN1J+i7NA27wha5maaodB2/oxfz7u5haetELN4pEKE094Lxij01oRYbEveR/D3utr6jupspChAmzshVW6u8U3CmNE7vgBsm6880mLLHUCJEajt6L7AHfdKOyyW/VtpsevWeolHbPCEJDIhnJ8hIYtNPZbMP/ebWsSBaIur1h2EanNY9HOhmID+U9IdwJO3oL8i5+ytFxnw7q74qqo8FdFoGjwdBKbp3d6GSPXmEbyBQ6f8bCVH/sYgo2reeqXl8iRdwBmBEsYEvQl1JzbO8kUCoSRvX7NE=
      on:
        tags: true

  - os: osx
    name: "Analyze Clang"
    osx_image: xcode11
    compiler: clang

    script:
      - git clone https://github.com/acidanthera/MacKernelSDK
      - src=$(/usr/bin/curl -Lfs https://raw.githubusercontent.com/acidanthera/Lilu/master/Lilu/Scripts/bootstrap.sh) && eval "$src" || exit 1
      - xcodebuild analyze -quiet -scheme BrightnessKeys -configuration Debug CLANG_ANALYZER_OUTPUT=plist-html CLANG_ANALYZER_OUTPUT_DIR="$(pwd)/clang-analyze" && [ "$(find clang-analyze -name "*.html")" = "" ]
      - xcodebuild analyze -quiet -scheme BrightnessKeys -configuration Release CLANG_ANALYZER_OUTPUT=plist-html CLANG_ANALYZER_OUTPUT_DIR="$(pwd)/clang-analyze" && [ "$(find clang-analyze -name "*.html")" = "" ]

